

import numpy as np
import pandas as pd
import talib as ta
import math
import csv
from array import *
import time
import matplotlib.pyplot as mp
from numpy import inf
import numpy as np
from timeit import default_timer as timer
import decimal
import random
from numba import jit
from numba import cuda
import numba
import statistics
import matplotlib.pyplot as plt
import warnings


def CSV_setup():
    print('DATA STORING SETUP COMMENCING')

    start = timer()    

    warnings.filterwarnings('ignore')
    
    
    ticker_csv_data = pd.read_csv('ticker_list_today.csv')
    #print(ticker_csv_data)
    
    ticker_csv_data = ticker_csv_data['Tickers'].to_numpy().tolist()
    #print("Full Ticker List:", ticker_csv_data) 
    
    #tickers = ['BA','NVDA','PTON','SABR','AAPL','MSFT','AMD','COST','MAR','PYPL','AEP']
    tickers = ticker_csv_data
    
    DATA_SOURCE = 'TRADINGVIEW'
    "OPTIONS: TRADINGVIEW"
    
    for ticker in tickers:        
        
        PMAX_csv_1 = 'Pmax_Algo_Data_collection_1_'+ticker+'_'+DATA_SOURCE+'.csv'     
        with open(PMAX_csv_1, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
            
        
        PMAX_csv_2 = 'Pmax_Algo_Data_collection_2_'+ticker+'_'+DATA_SOURCE+'.csv'      
        with open(PMAX_csv_2, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
            
        
        PMAX_csv_3 = 'Pmax_Algo_Data_collection_3_'+ticker+'_'+DATA_SOURCE+'.csv'      
        with open(PMAX_csv_3, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
            
        
        PMAX_csv_4 = 'Pmax_Algo_Data_collection_4_'+ticker+'_'+DATA_SOURCE+'.csv'             
        with open(PMAX_csv_4, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
            
        PMAX_csv_5 = 'Pmax_Algo_Data_collection_5_'+ticker+'_'+DATA_SOURCE+'.csv'              
        with open(PMAX_csv_5, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
            
        PMAX_csv_6 = 'Pmax_Algo_Data_collection_6_'+ticker+'_'+DATA_SOURCE+'.csv'               
        with open(PMAX_csv_6, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
            
        PMAX_csv_7 = 'Pmax_Algo_Data_collection_7_'+ticker+'_'+DATA_SOURCE+'.csv'               
        with open(PMAX_csv_7, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
            
        PMAX_csv_8 = 'Pmax_Algo_Data_collection_8_'+ticker+'_'+DATA_SOURCE+'.csv'    
        with open(PMAX_csv_8, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_9 = 'Pmax_Algo_Data_collection_9_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_9, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_10 = 'Pmax_Algo_Data_collection_10_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_10, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_11 = 'Pmax_Algo_Data_collection_11_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_11, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
         
        PMAX_csv_12 = 'Pmax_Algo_Data_collection_12_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_12, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_13 = 'Pmax_Algo_Data_collection_13_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_13, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_14 = 'Pmax_Algo_Data_collection_14_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_14, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_15 = 'Pmax_Algo_Data_collection_15_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_15, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_16 = 'Pmax_Algo_Data_collection_16_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_16, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_17 = 'Pmax_Algo_Data_collection_17_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_17, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_18 = 'Pmax_Algo_Data_collection_18_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_18, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_19 = 'Pmax_Algo_Data_collection_19_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_19, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_20 = 'Pmax_Algo_Data_collection_20_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_20, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_21 = 'Pmax_Algo_Data_collection_21_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_21, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_22 = 'Pmax_Algo_Data_collection_22_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_22, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_23 = 'Pmax_Algo_Data_collection_23_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_23, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_24 = 'Pmax_Algo_Data_collection_24_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_24, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_25 = 'Pmax_Algo_Data_collection_25_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_25, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_26 = 'Pmax_Algo_Data_collection_26_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_26, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_27 = 'Pmax_Algo_Data_collection_27_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_27, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_28 = 'Pmax_Algo_Data_collection_28_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_28, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_29 = 'Pmax_Algo_Data_collection_29_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_29, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_30 = 'Pmax_Algo_Data_collection_30_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_30, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_31 = 'Pmax_Algo_Data_collection_31_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_31, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_32 = 'Pmax_Algo_Data_collection_32_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_32, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_33 = 'Pmax_Algo_Data_collection_33_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_33, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_34 = 'Pmax_Algo_Data_collection_34_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_34, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_35 = 'Pmax_Algo_Data_collection_35_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_35, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_36 = 'Pmax_Algo_Data_collection_36_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_36, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_37 = 'Pmax_Algo_Data_collection_37_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_37, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_38 = 'Pmax_Algo_Data_collection_38_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_38, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_39 = 'Pmax_Algo_Data_collection_39_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_39, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        PMAX_csv_40 = 'Pmax_Algo_Data_collection_40_'+ticker+'_'+DATA_SOURCE+'.csv'
        with open(PMAX_csv_40, 'a', newline='') as csvfile:
            my_writer = csv.writer(csvfile)
            my_writer.writerow(("Ticker","PMax_Letter_Grade","ATR Multiplier","Tillson T3 Length","T3a1 Tillson Volume","ATR Length","RSI Length","Net Profit All","Total Gross Profit","Total Gross Loss","Portfolio Max","Portfolio Max Deviation","Portfolio Max Drawdown Percentage","Buy and Hold Return","Sharpe Ratio","Standard Deviation","Sortino Ratio","Profit Factor","Max Contracts Held","Open Profit Loss","Commission Paid","Total Closed Trades","Total Open Trades","Number of Winning Trades","Number of Losing Trades","Percent Profitable","Average Trade","Average Winning Trades","Average Losing Trades","Ratio Average Win/Loss","Largest Winning Trade","Largest Losing Trade","Average of Bars in Each Trade","Average Number of Winning Bars","Average Number of Losing Bars","Margin Calls","Net Profit Long","Gross Profit Long","Gross Loss Long","Profit Factor Long","Max Contracts Held Long","Commission Paiad Long","Total Closed Trades Long","Total Open Trades Long","Number of Winning Trades Long","Number of Losing Trades Long","Percent Profitable Long","Average Trade Long","Average Winning Trades Long","Average Losing Trades Long","Ratio Average Win/Loss Long","Largest Winning Trade Long","Largest Losing Trade Long","Average Number of Bars In Each Trade Long","Average Number of Winning Bars Long","Average Number of Losing Bars Long","Net Profit Short","Gross Profit Short","Gross Loss Short","Profit Factor Short","Max Contracts Held Short","Commission Paiad Short","Total Closed Trades Short","Total Open Trades Short","Number of Winning Trades Short","Number of Losing Trades Short","Percent Profitable Short","Average Trade Short","Average Winning Trades Short","Average Losing Trades Short","Ratio Average Win/Loss Short","Largest Winning Trade Short","Largest Losing Trade Short","Average Number of Bars In Each Trade Short","Average Number of Winning Bars Short","Average Number of Losing Bars Short","Trend Percentage","Net Profit Percetnage","MaxDrawdown/NetProfit Ratio", "Stop Loss Percentage"))
        
        
        
         
         
        
    
    
    ####print("without GPU:", timer()-start)    
    print("DATA STORING SETUP COMPLETE")  
              
CSV_setup()                              
                       
            
            
            
            
        
        
        
        
        
    
    
    
    
    
    
    
    
    
    